# Site settings
title: Documentation
email: admin@open-classifieds.com
description: > # this means to ignore newlines until "baseurl:"
  Description
baseurl: "http://docs.yclas.com"
url: ""
twitter_username: openclassifieds
github_username:  open-classifieds

# Build settings
markdown: kramdown

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-55615337-3'
